spring:
  application:
    name: libros
  datasource:
    url: jdbc:h2:mem:librosdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true


